import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { authorKaneTest, parseKaneGenerateResult } from "../src/author.mjs";

test("parses a completed Kane authoring stream and keeps the generated snapshot", () => {
  const result = parseKaneGenerateResult({
    stdout: [
      JSON.stringify({ type: "generate_start", request_id: "req-17" }),
      JSON.stringify({ type: "generate_snapshot", scenario_count: 1, case_count: 2, scenarios: [{ title: "Add task", cases: [{ title: "Add a task" }] }] }),
      JSON.stringify({ type: "generate_done", request_id: "req-17", status: "completed" }),
    ].join("\n"),
    stderr: "",
    exitCode: 0,
  });
  assert.equal(result.status, "COMPLETED");
  assert.equal(result.requestId, "req-17");
  assert.equal(result.scenarioCount, 1);
  assert.equal(result.caseCount, 2);
  assert.equal(result.scenarios[0].title, "Add task");
});

test("keeps Kane clarifications as a pending authoring result", () => {
  const result = parseKaneGenerateResult({
    stdout: [
      JSON.stringify({ type: "generate_start", request_id: "req-18" }),
      JSON.stringify({ type: "generate_clarification", text: "Which environment should the test use?" }),
      JSON.stringify({ type: "generate_done", request_id: "req-18", status: "completed" }),
    ].join("\n"),
    stderr: "",
    exitCode: 0,
  });
  assert.equal(result.status, "CLARIFICATION");
  assert.match(result.clarification, /Which environment/);
});

test("runs Kane generate and save without hand-writing the test file", async () => {
  const root = mkdtempSync(join(tmpdir(), "elenchos-author-flow-"));
  const fakeKane = [
    "const { mkdirSync, writeFileSync } = require('node:fs');",
    "const { join } = require('node:path');",
    "const args = process.argv.slice(1);",
    "if (args.includes('--save')) {",
    "  const out = args[args.indexOf('--out') + 1];",
    "  mkdirSync(out, { recursive: true });",
    "  const file = join(out, 'generated_test.md');",
    "  writeFileSync(file, '# Generated by Kane\\n');",
    "  process.stdout.write(JSON.stringify({ type: 'generate_save_result', saved: [file], suite_dir: out }) + '\\n');",
    "  process.stdout.write(JSON.stringify({ type: 'generate_done', request_id: 'req-19', status: 'completed', suite_dir: out }) + '\\n');",
    "} else {",
    "  process.stdout.write(JSON.stringify({ type: 'generate_start', request_id: 'req-19' }) + '\\n');",
    "  process.stdout.write(JSON.stringify({ type: 'generate_snapshot', scenario_count: 1, case_count: 1, scenarios: [] }) + '\\n');",
    "  process.stdout.write(JSON.stringify({ type: 'generate_done', request_id: 'req-19', status: 'completed' }) + '\\n');",
    "}",
  ].join("\n");
  try {
    const fakePath = join(root, "fake-kane.cjs");
    writeFileSync(fakePath, fakeKane, "utf8");
    const result = await authorKaneTest({
      task: {
        id: "author-flow",
        title: "Author flow",
        description: "Generate a test",
        setup: ["Start the app"],
        preconditions: { page: "/" },
        acceptanceCriteria: [{ id: "AC-001", description: "The page loads" }],
        verification: {},
      },
      cwd: root,
      outputPath: "tests/author-flow_test.md",
      config: { command: fakePath },
    });
    assert.equal(result.status, "COMPLETED");
    assert.equal(result.requestId, "req-19");
    assert.equal(readFileSync(join(root, "tests", "author-flow_test.md"), "utf8"), "# Generated by Kane\n");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("continues an existing Kane authoring request through refine and save", async () => {
  const root = mkdtempSync(join(tmpdir(), "elenchos-author-refine-"));
  const fakeKane = [
    "const { mkdirSync, writeFileSync } = require('node:fs');",
    "const { join } = require('node:path');",
    "const args = process.argv.slice(1);",
    "if (args.includes('--save')) {",
    "  const out = args[args.indexOf('--out') + 1];",
    "  mkdirSync(out, { recursive: true });",
    "  const file = join(out, 'refined_test.md');",
    "  writeFileSync(file, '# Refined by Kane\\n');",
    "  process.stdout.write(JSON.stringify({ type: 'generate_save_result', saved: [file] }) + '\\n');",
    "  process.stdout.write(JSON.stringify({ type: 'generate_done', request_id: 'req-20', status: 'completed' }) + '\\n');",
    "} else {",
    "  if (!args.includes('--refine') || args[args.indexOf('--req') + 1] !== 'req-20') process.exit(4);",
    "  process.stdout.write(JSON.stringify({ type: 'generate_snapshot', scenario_count: 1, case_count: 1, scenarios: [] }) + '\\n');",
    "  process.stdout.write(JSON.stringify({ type: 'generate_done', request_id: 'req-20', status: 'completed' }) + '\\n');",
    "}",
  ].join("\n");
  try {
    const fakePath = join(root, "fake-kane.cjs");
    writeFileSync(fakePath, fakeKane, "utf8");
    const result = await authorKaneTest({
      task: { id: "refine-flow", title: "Refine flow", acceptanceCriteria: [{ id: "AC-001", description: "The page loads" }], verification: {} },
      cwd: root,
      outputPath: "tests/refine-flow_test.md",
      config: { command: fakePath },
      refine: "Use the local page",
      requestId: "req-20",
    });
    assert.equal(result.status, "COMPLETED");
    assert.equal(readFileSync(join(root, "tests", "refine-flow_test.md"), "utf8"), "# Refined by Kane\n");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
